name: Documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
    - name: Restore .NET tools
      run: dotnet tool restore
    - name: Paket install
      run: dotnet paket install
    - name: Build docs, via build_docs.sh
      run: ./build_docs.sh
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
